-- Run once in the Supabase project's SQL editor (Dashboard -> SQL Editor).
-- Indexes every report generated by services/storage_service.py so the
-- deployed UI can list and re-download every run, from any browser/device.
-- Pair with a private Storage bucket named "reports" (or whatever
-- SUPABASE_BUCKET is set to) created via Dashboard -> Storage -> New bucket
-- (leave "Public bucket" OFF — downloads always go through signed URLs).

create table if not exists reports (
  id uuid primary key default gen_random_uuid(),
  company_name text not null,
  md_path text not null,
  docx_path text not null,
  provider text not null,
  model text,
  prompt_version text not null,
  stop_reason text,
  truncated boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists reports_created_at_idx on reports (created_at desc);
